#!D:\Ideas\Daena_old_upgrade_20251213\venv_daena_audio_py310\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
