import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { usePageTitle } from '@/hooks/usePageTitle'

const EFFECTIVE_DATE = 'March 22, 2026'
const COMPANY = 'MAS-AI Technologies Inc.'
const JURISDICTION = 'Ontario, Canada'
const CONTACT_EMAIL = 'legal@mas-ai.co'

export function TermsPage() {
  usePageTitle('Terms of Service')

  return (
    <div className="min-h-screen bg-midnight-900 text-starlight-200">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Back link */}
        <Link
          to="/login"
          className="inline-flex items-center gap-1.5 text-sm text-starlight-400 hover:text-starlight-200 transition-colors mb-8"
        >
          <ArrowLeft size={14} />
          Back
        </Link>

        <h1 className="font-display text-3xl font-bold text-starlight-100 mb-2">Terms of Service</h1>
        <p className="text-sm text-starlight-400 mb-10">Effective: {EFFECTIVE_DATE}</p>

        <div className="space-y-8 text-sm leading-relaxed text-starlight-300">
          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">1. Acceptance of Terms</h2>
            <p>
              By creating an account, accessing, or using Daena (the "Service"), you agree to be bound by these Terms of Service ("Terms"),
              our <Link to="/privacy" className="text-primary-400 hover:text-primary-500 underline">Privacy Policy</Link>, and
              our Acceptable Use Policy. If you do not agree, do not use the Service.
            </p>
            <p className="mt-2">
              You must be at least 18 years old or the age of majority in your jurisdiction to use this Service.
              By registering, you represent and warrant that you meet this requirement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">2. Description of Service</h2>
            <p>
              Daena is a governed multi-agent AI orchestration platform provided by {COMPANY}. The Service enables users to
              interact with AI models from multiple providers, manage AI departments, and execute governed workflows.
              The Service is provided "as is" and "as available."
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">3. Account Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You are responsible for all activities that occur under your account.</li>
              <li>You must immediately notify us of any unauthorized use of your account.</li>
              <li>You may not share your account or transfer it to another person without our written consent.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">4. AI-Generated Content</h2>
            <p className="font-medium text-starlight-100 mb-2">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>AI outputs may be inaccurate.</strong> Content generated by AI models through Daena may contain errors,
                hallucinations, outdated information, or biased perspectives. You are solely responsible for reviewing,
                verifying, and validating all AI-generated content before relying on it.
              </li>
              <li>
                <strong>No professional advice.</strong> AI-generated content does not constitute legal, medical, financial,
                or any other form of professional advice. Consult qualified professionals for such matters.
              </li>
              <li>
                <strong>Third-party model providers.</strong> Daena integrates with third-party AI model providers (including
                but not limited to OpenAI, Anthropic, Google, Meta, and others). Your use of these models is also subject
                to their respective terms of service.
              </li>
              <li>
                <strong>No guarantee of availability.</strong> Specific AI models or providers may become unavailable at any
                time without notice. We are not responsible for the availability or performance of third-party services.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Violate any applicable law, regulation, or third-party rights.</li>
              <li>Generate, distribute, or store illegal, harmful, or abusive content.</li>
              <li>Attempt to circumvent governance policies, security controls, or access restrictions.</li>
              <li>Reverse-engineer, decompile, or disassemble any part of the Service.</li>
              <li>Introduce malicious code, viruses, or other harmful materials.</li>
              <li>Use the Service to develop competing products without written authorization.</li>
              <li>Exceed reasonable usage limits or engage in activities that degrade service performance.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">6. Intellectual Property</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Our IP.</strong> The Service, including its software, design, architecture (including the patent-pending
                PhiLattice Architecture and NBMF system), trademarks, and documentation, is owned by {COMPANY} and protected
                by intellectual property laws.
              </li>
              <li>
                <strong>Your content.</strong> You retain ownership of content you input into the Service. By using the Service,
                you grant us a limited license to process your content solely for the purpose of providing the Service.
              </li>
              <li>
                <strong>AI-generated output.</strong> Ownership of AI-generated content is subject to applicable laws and the
                terms of the underlying model providers. We make no claim of ownership over AI-generated outputs.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">7. Data and Privacy</h2>
            <p>
              Your use of the Service is subject to our <Link to="/privacy" className="text-primary-400 hover:text-primary-500 underline">Privacy Policy</Link>,
              which describes how we collect, use, and protect your data. By using the Service, you consent to our data practices
              as described therein.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">8. Limitation of Liability</h2>
            <p className="uppercase text-xs text-starlight-400 tracking-wide mb-2">
              PLEASE READ THIS SECTION CAREFULLY.
            </p>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY}, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS,
              SUPPLIERS, OR AFFILIATES, SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
              DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES,
              RESULTING FROM:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Your access to or use of or inability to access or use the Service;</li>
              <li>Any conduct or content of any third party on the Service, including AI-generated content;</li>
              <li>Any content obtained from the Service;</li>
              <li>Unauthorized access, use, or alteration of your transmissions or content;</li>
              <li>Decisions made or actions taken based on AI-generated content.</li>
            </ul>
            <p className="mt-3">
              IN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE GREATER OF ONE HUNDRED CANADIAN DOLLARS (CAD $100.00)
              OR THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">9. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless {COMPANY} and its officers, directors, employees, and agents
              from and against any claims, damages, obligations, losses, liabilities, costs, or debt arising from: (a) your
              use of the Service; (b) your violation of these Terms; (c) your violation of any third-party right, including
              any intellectual property or privacy right; or (d) any claim that your use of the Service caused damage to a third party.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">10. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS
              OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
              NON-INFRINGEMENT, OR COURSE OF PERFORMANCE. {COMPANY} DOES NOT WARRANT THAT THE SERVICE WILL FUNCTION
              UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">11. Termination</h2>
            <p>
              We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any
              reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the
              Service will cease immediately. You may request deletion of your data in accordance with our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario and the
              federal laws of Canada applicable therein, without regard to its conflict of law provisions. Any disputes
              arising under these Terms shall be subject to the exclusive jurisdiction of the courts of {JURISDICTION}.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">13. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting
              the updated Terms on the Service with a new effective date. Your continued use of the Service after such changes
              constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-starlight-100 mb-3">14. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary-400 hover:text-primary-500 underline">
                {CONTACT_EMAIL}
              </a>.
            </p>
          </section>

          <div className="border-t border-white/5 pt-6 mt-10">
            <p className="text-xs text-starlight-500">
              {COMPANY} &middot; {JURISDICTION} &middot; {EFFECTIVE_DATE}
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default TermsPage
